name: train-my-model
on: [push]
jobs:
  train:
    runs-on: [self-hosted, cml]
    steps:
      - uses: actions/checkout@v3
      - name: Installing requirements
        run: |
          #echo 'Hi from CML!' >> report.md
          #cml-send-comment report.md
          ls 
          pip install -r icu_outcome_prediction/requirements.txt
