name: train-my-model
on: [push]
jobs:
  train:
    runs-on: [self-hosted, cml]
    steps:
      - uses: actions/checkout@v3
      - name: Installing requirements
        run: |
          #echo 'Hi from CML!' >> report.md
          #cml-send-comment report.md
          ls 
          echo "_______________________________________"
          pip install --upgrade setuptools
          pip install --upgrade pip
          pip install -r icu_outcome_prediction/requirements.txt
      - name: Training the model
        run: |
          python3 icu_outcome_prediction/src/models/train_model.py